### ISSUE TITLE
Typo in class name in the 3 graphs: RegisterdModel -> RegisteredModel

### ISSUE THREAD

**Issue by tiansiyuan** [kubeflow/model-registry#118]
**Describe the bug**

**To Reproduce**
1. Do this '...'
2. Do that '....'
3. See error

**Expected behavior**

**Additional context**

**Comment by tarilabs** [comment]
@tiansiyuan thank you for this report. We are inviting people to contribute an entry to the Adopters file:
https://github.com/kubeflow/model-registry/blob/main/ADOPTERS.md
to foster the Model Registry component and the Kubeflow community.
If you could add your name there, would be awesome!

**Comment by tiansiyuan** [comment]
@tarilabs Thank you for your invitation. 

PR is created.

**Comment by tarilabs** [comment]
... and PR is merged :) thanks again!
