### ISSUE TITLE
Support for Multi-Tenancy

### ISSUE THREAD

**Issue by hungcao0402** [kubeflow/model-registry#120]
Does the model-registry support multi-tenancy? If not, is there a way to implement it?

**Comment by tarilabs** [comment]
Not at present; the reason for being an Alpha component is to gather feedback around these functionalities.

Multi-tenancy or multiple-tenant too, see also:
- highlight in: https://github.com/kubeflow/kubeflow/issues/7396#:~:text=Support%20multi%2Dtenancy%0AMl%2Dmetadata%20should%20support%20multi%2Dtenant%20metadata%20resources
- thread in: https://github.com/kubeflow/community/pull/682
