### ISSUE TITLE
Introduce image Container Registry use

### ISSUE THREAD

**Issue by tarilabs** [kubeflow/model-registry#23]
Ref KF community meeting 2024-02-27

We note the KF community feedback suggesting to make use of GitHub Container Registry (part of "GitHub Packages") for publishing Container Images using GitHub Actions. Eventually, GH CR images can be synced to DockerHub https://hub.docker.com/u/kubeflow by raising request to KF community.

This issue tracks steps required to enable Container Image production and publication, similarly to what was available in ODH+Quay.

Acceptance criteria:
- [x] ensure this GHA works as expected: https://github.com/kubeflow/model-registry/blob/main/.github/workflows/build-image-pr.yml
- [x] modify this GHA and related script _to publish with _ dockerhub Container Registry_ as needed: https://github.com/kubeflow/model-registry/blob/main/.github/workflows/build-image-pr.yml
(this GHA and related script at the time of writing were used to publish to Quay)
- [x] re-enable this workflow: https://github.com/kubeflow/model-registry/actions/workflows/build-and-push-image.yml 
- [x] verify Container Image get published in Container Registry

Stretch goals:
- [ ] modify Docker file, makefile, etc to account for cross-platform build (see [comment](https://github.com/kubeflow/model-registry/issues/23#issuecomment-1968119217) for examples)
- [ ] ask KF community leads to enable sync from GH CR to DockerHub for model-registry

**Comment by thesuperzapper** [comment]
@tarilabs since we are starting out fresh, can you please ensure you cross-compile for ARM64 in addition to AMD64?

Depending on how many container images you plan to have, you may or may not need something as complex as what we do for Kubeflow Notebooks. But either way, here are some links you might find useful that show using QEMU emulation and Docker BuildX:

- GitHub Actions:
    - GHA Template (`workflow_call`): 
        - https://github.com/kubeflow/kubeflow/blob/master/.github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
    - GHA Root:
        - https://github.com/kubeflow/kubeflow/blob/master/.github/workflows/example_notebook_servers_publish.yaml
- Makefile:
    - Makefile Template: 
        - https://github.com/kubeflow/kubeflow/blob/master/components/example-notebook-servers/common.mk
    - Makefile Root: 
        - https://github.com/kubeflow/kubeflow/blob/master/components/example-notebook-servers/Makefile

**Comment by tarilabs** [comment]
@thesuperzapper that's a very good point Mathew thanks especially for sharing examples of cross-platforms container image build!

While we have an extensive Integration Test suite, e2e testing on arm will be limited atm due to the MLMD image unavailability (for arm). That accounted for, we can start early (as you pointed out) to account for cross-platform build so we can be prepared when all components are available on arm imho.

**Comment by thesuperzapper** [comment]
@tarilabs well... I have a Christmas present for you regarding ARM64 support in the MLMD image.

I made a PR upstream to introduce ARM64 support, and also made a fork and published an ARM image (built under GHA emulation) for my own project ([deployKF](https://www.deploykf.org/)) until it gets merged upstream.

For more information, please see:

- My `ml-metadata` PR:
    - https://github.com/google/ml-metadata/pull/188
- The associated KFP Issue:
    - https://github.com/kubeflow/pipelines/issues/10308
- The deployKF fork of the `ml-metadata` repo:
    - https://github.com/deployKF/ml-metadata
- Forked `gcr.io/tfx-oss-public/ml_metadata_store_server` image (with ARM/AMD): 
    - [`ghcr.io/deploykf/ci/ml_metadata_store_server:sha-cad0c56`](https://github.com/deployKF/ml-metadata/pkgs/container/ci%2Fml_metadata_store_server)

This is all assuming you are talking about `ghcr.io/deploykf/ci/ml_metadata_store_serve` image needing ARM64 support, and not some other part of `ml-metadata` (which may actually already support it).

**Comment by tarilabs** [comment]
dockerhub token should be setup for this repo, as:
```
DOCKERHUB_USERNAME
DOCKERHUB_TOKEN
```

**Comment by tarilabs** [comment]
@rchincha thank you for reaching out, I invite you to comment the above on the Model Registry proposal for Kubeflow, here: https://github.com/kubeflow/community/pull/682

There is recurrent community call for Kubeflow: https://www.kubeflow.org/docs/about/community/#kubeflow-community-call and I strongly encourage you to engage at that level to spread best awareness of your initiative.

There is also bi-weekly call for Model Registry, as you can find in the above linked calendar.

Hope this helps! :)

**Comment by tarilabs** [comment]
> - ensure this GHA works as expected: https://github.com/kubeflow/model-registry/blob/main/.github/workflows/build-image-pr.yml
> - verify Container Image get published in Container Registry

demonstrated by: https://hub.docker.com/layers/kubeflow/model-registry/main-dc872c1/images/sha256-24e934a1ab01d07862fb5c8b98154281ea2c981cbc257dbd9b0b469661dab093?context=explore
and up the tree

> - modify this GHA and related script _to publish with _ dockerhub Container Registry_ as needed: https://github.com/kubeflow/model-registry/blob/main/.github/workflows/build-image-pr.yml
(this GHA and related script at the time of writing were used to publish to Quay)

was done with:
- https://github.com/kubeflow/model-registry/commit/c9bdfc21ab5495270b1f4a6b144958e23a88b250
- https://github.com/kubeflow/model-registry/commit/784c9fb68bd2326b6f3c1efd99bb4455bfe1be84#diff-c7cbc4a36f236b91dd212d03b3a15dd7ea80de2a647ac34aeec2ba9bf70f8fc4

> - re-enable this workflow: https://github.com/kubeflow/model-registry/actions/workflows/build-and-push-image.yml 

as demonstrated above, is re-enabled.
