### ISSUE TITLE
Command `make test` not working with Fedora 40

### ISSUE THREAD

**Issue by Al-Pragliola** [kubeflow/model-registry#268]
I followed the instructions from CONTRIBUTING.md, section [Podman], but I had to make additional steps to make it work:

- Export the additional environment variable to make testcontainers work with podman and SELinux:

```bash
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock
```

- Add `Privileged: true` to https://github.com/kubeflow/model-registry/blob/main/internal/testutils/test_container_utils.go#L89-L92

I don't really like adding privileged permissions to the test container, but I couldn't find another way to make it work.

I will open a PR soon addressing this issue

**Comment by tarilabs** [comment]
there might be also some possibilities by avoiding the use of Ryuk, but I didn't have chance to investigate in this direction fully; thought mentioning if you wanted to try digging a bit in this direction!

**Comment by Al-Pragliola** [comment]
I also tried disabling ryuk, but SELinux prevents the (metadata) container from reading the contents of `conn_config.pb`, so it uses the in-memory db, which does not persist the test seed data, making all the tests fail, with or without ryuk, I still need the Privileged set to true.
