### ISSUE TITLE
Expose update methods on Python client

### ISSUE THREAD

**Issue by isinyaaa** [kubeflow/model-registry#319]
**Is your feature request related to a problem? Please describe.**
Clients currently need to work their way through the core API in order to update models:

```py
from model_registry import ModelRegistry

client = ModelRegistry(...)
rm = client.register_model("mymodel", "s3://...", ...)

rm.description = "yada yada yada"

client.async_runner(
    client._api.upsert_registered_model(rm)
)
```

**Describe the solution you'd like**
A simple solution would be to have helper methods:

```py
from model_registry import ModelRegistry

client = ModelRegistry(...)
rm = client.register_model("mymodel", "s3://...", ...)

rm.description = "yada yada yada"

client.update_registered_model(rm)
```

**Describe alternatives you've considered**
A more Pythonic approach would be to completely change our approach to user-facing MR types, allowing for something like

```py
from model_registry import ModelRegistry

client = ModelRegistry(...)
rm = client.register_model("mymodel", "s3://...", ...)

rm.description = "yada yada yada"

rm.update()
```

**Additional context**
This would be helpful to cover user stories on the high-level Python client.

**Comment by tarilabs** [comment]
At first glance, I believe former is also more explicit.

In other contexts, I would prefer the latter, especially when it's about ORM entities behave in that way (in most used ORMs) but we're actually over the wire on REST.

We could design client to accept polymorphic `client.update(RegisteredModel | ModelVersion | ...)` etc.

**Comment by tarilabs** [comment]
I'm going to close this as I believe resolved by https://github.com/kubeflow/model-registry/pull/344
