### ISSUE TITLE
Introduce dependency license monitoring

### ISSUE THREAD

**Issue by tarilabs** [kubeflow/model-registry#323]
This project onboarded as Apache-2.0, [see original thread](https://github.com/kubeflow/community/issues/685#issuecomment-1889559126). 

We have received questions about the dependencies' license compatibility, for which we referenced: https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist

In this repo, we have:
- main REST Model Registry server: Go
- MR Python client: Python
- UI: React, Node
- BFF: Go
- CSI: Go

(we could have more in the future more)

To help with automating on the dependency checks,
👉 we propose to introduce FOSSA scanning in this repo, from the list of tools CNCF can support with: https://contribute.cncf.io/resources/project-services/hosted-tools/#tools

---

If you are a Kubeflow member reading this issue and you need to be added in the FOSSA tool:

- general access to CNCF's FOSSA which is a prerequisite is [to be requested via CNCF service desk](https://contribute.cncf.io/resources/project-services/hosted-tools/#tools:~:text=Most%20services%20can%20be%20requested%20through%20a%20Service%20Desk%20ticket): ask a KFSC representative to manage the service desk request for you/your KF project.
- then, you can reach out to myself, @rimolive and @terrytangyuan to be added in the existing Fossa team "Kubeflow" in the CNCF's FOSSA, or ask a KFSC representative to manage the service desk request for you/your KF project 

Suggested steps for new projects/repos:

1. ensure the Maintainer is added to the correct Team (in our case, "Kubeflow" Team)
![Screenshot 2024-09-10 at 09 54 36](https://github.com/user-attachments/assets/037d555e-af06-451f-89dd-6c412dc89c67)

2. the Maintainer is to create a "push only" token api key, [see example](https://github.com/kubeflow/model-registry/pull/324/files#diff-472dd216a27f2e558659b83ec1d8874189994adca4da6eefb3b00f63dab93fd2R16).

3. the Maintainer should first use the fossa cli with the `--team` flag for the desired repo, and the appropriate configurations keys from within a [.fossa.yml](https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md) file.
That would spawn a new Fossa project in the CNCF Org _and_ assign it to the Fossa Team "Kubeflow", at once.

> [!TIP]
> These newly created Fossa projects would appear within the intended "Kubeflow" Fossa Team, and since we share team admin, should have the appropriate permissions to modify them, such as adding new revision of the project (i.e. new scans)
> The issue may arise when a _new fossa project is created outside of the team_ or if an attempt is made to modify an existing project (by adding it to a team, for instance). At this point, we lack CNCF Organizational role sufficient permissions, as in CNCF FOSSA Organization we have only read rights, but write rights only under the given "Kubeflow" FOSSA Team

- When using the fossa cli, you can specify the name using either the `--title` flag which in Model Registry we set to the github location (`https://github.com/kubeflow/model-registry`), or let FOSSA attempt to automatically determine the title from the VCS.
- To ensure consistency, is best to utilize the `--project` flag when used from the cli, and `project: key` when used from the gha. In our case we set it to the `github.com/kubeflow/model-registry` per fossa conventions.
- Additional settings to be considered are `project.name: key` flag within the `.fossa.yml` file. That should allow it to be uploaded to the same project every time.
You can also use `revision.branch` to the same effect if the branch can not be determined automatically.

4. only after having used the fossa cli, [setup the GHA](https://github.com/fossas/fossa-action) (so it would update a revision to an existing Project already assigned to a Team)

> [!NOTE] 
> API keys are tied to the Account that created them and inherit their permissions. Should the account permissions change, the token's will as well. This means if the Maintainer from step1 leaves the Fossa team, the remaining Kubeflow project Maintainers will need to go through these steps again to ensure the GHA has the correct push-only token api key, to upload to fossa a new revision.

**Comment by rareddy** [comment]
apart from the benefits from scanning for the project which I already receive, is there any reason why I should add my name?

**Comment by tarilabs** [comment]
Follow-ed up with FOSSA helpdesk since I'm not able to add the repo to the Kubeflow team

![Screenshot 2024-09-04 at 12 12 01](https://github.com/user-attachments/assets/7be99331-f466-4539-abbd-f92d2cbe8cd7)
![Screenshot 2024-09-04 at 12 12 42](https://github.com/user-attachments/assets/51a70004-58de-41e2-856a-f6f06ced48ca)

![image](https://github.com/user-attachments/assets/e24a9a6d-b7cc-4aca-9275-d0b3305a67d1)

**Comment by tarilabs** [comment]
this is now working as expected in https://github.com/kubeflow/model-registry/pull/324 thanks from the support of David with `TKT-11475`.
