### ISSUE TITLE
UI CI fails with uncommited changes

### ISSUE THREAD

**Issue by tarilabs** [kubeflow/model-registry#405]
**Describe the bug**
At time the UI CI reports uncommitted changes 

**To Reproduce**
1. See https://github.com/kubeflow/model-registry/actions/runs/10948937500/job/30401082009?pr=403

**Expected behavior**
Not failing.

**Additional context**
Experienced both by @isinyaaa and myself with #403 and #404

**Comment by tarilabs** [comment]
@ederign can you kindly take a look?
Restarting the job a couple of times made it not fail anymore

**Comment by tarilabs** [comment]
@ederign thank you. With @isinyaaa yesterday the git ignore in https://github.com/kubeflow/model-registry/pull/403/commits/56c5ddb60d11b90162a9d67f07b2fcca1c2498e7 was added, my question would be to have some additional pair of eyes to check if anything else needed.

**Comment by ederign** [comment]
Thank you, @isinyaaa, for the quick fix! That explains why I can't reproduce it locally! :)

I did a small FUP cleanup https://github.com/kubeflow/model-registry/pull/408/files

**Comment by ederign** [comment]
@tarilabs as https://github.com/kubeflow/model-registry/pull/408 is merged, I believe we can close this one.

**Comment by tarilabs** [comment]
thank you so much both of you @isinyaaa @ederign
