### ISSUE TITLE
Delete Registered model 

### ISSUE THREAD

**Issue by MidhunSaiReddy03** [kubeflow/model-registry#468]
I can't able to delete my registered model,  is there any method to delete the model or is there any alternative method to do that help me with this

**Comment by MidhunSaiReddy03** [comment]
can i get some more clarity on this there is no status parameter in my model

**Comment by tarilabs** [comment]
@MidhunSaiReddy03 thank you for this report. We are inviting people to contribute an entry to the Adopters file:
https://github.com/kubeflow/model-registry/blob/main/ADOPTERS.md
to foster the Model Registry component and the Kubeflow community.
If you could add your name there, would be awesome!
