### ISSUE TITLE
chore: use matrix of k8s versions with KinD e2e testing

### ISSUE THREAD

**Issue by tarilabs** [kubeflow/model-registry#614]
during today's KF Release meeting (2024-12-02) @andreyvelich raised a relevant point that WGs should strongly consider running matrix testing of the K8s versions for their own e2e tests

where the K8s versions are identified by the Platform WG, for example here: https://github.com/kubeflow/community/issues/767

when declined on this MR repo, our main e2e test is here: https://github.com/kubeflow/model-registry/blob/d816da7ed807237a5a1b4541f423a1b6fd13d6af/.github/workflows/python-tests.yml#L68

so I would propose for said GHA to test against the necessary K8s version by configuring the KinD action appropriately: https://github.com/kubeflow/model-registry/blob/d816da7ed807237a5a1b4541f423a1b6fd13d6af/.github/workflows/python-tests.yml#L124-L127 from the matrix

I also believe this matrix testing of K8s shall be done only for 1 python version, and only when merged on main (ie not on every PR, to avoid eccessive workload from github)

**Comment by andreyvelich** [comment]
FYI, here is the matrix we use to run multiple Kubernetes and Python versions for Training Operator: https://github.com/kubeflow/training-operator/blob/adc972e1816f6489d5109a67d9ca3532de7175e3/.github/workflows/integration-tests.yaml#L29-L55
