### ISSUE TITLE
Misleading reference to DELETE operations in OpenAPI schema

### ISSUE THREAD

**Issue by dmartinol** [kubeflow/model-registry#63]
**Describe the bug**
The OpenAPI schema includes the `DELETE` operation for some of the managed paths, but delete services are not really implemented.

**To Reproduce**
See an example  of misleading description [here](https://github.com/kubeflow/model-registry/blob/5f7fac0f1d98dc3daa0027801dc365ac7e26814c/api/openapi/model-registry.yaml#L89).

Note that there is no `delete` operation under these paths.

Also, if we try to `curl -X DELETE`, it returns `HTTP/1.1 405 Method Not Allowed ` 

**Expected behavior**
Either implement the described operations or fix the documentation.

**Comment by tarilabs** [comment]
Thank you for reporting this @dmartinol ; as explained, Google ML-Metadata (which Model Registry is based on), does not support deletion semantic. We get support only of status change. As you correctly say, the `description` should be reflected.

> The OpenAPI schema includes the DELETE operation for some of the managed paths, but delete services are not really implemented.

There is no entry in OpenAPI for `delete:` _verb_ in https://github.com/kubeflow/model-registry/blob/main/api/openapi/model-registry.yaml

This is to be reflected basically in all textual documentation.
